# Generated automatically from Makefile.in by configure.
ALL: default
##### User configurable options #####
PEXDIR      = pelcrexamples
ARCH        = LINUX
#MPIR_HOME   = /mpi-share/current-mpi
MPIR_HOME  = /usr/local
CC=$(MPIR_HOME)/bin/mpicc
CCP         = $(MPIR_HOME)/bin/mpiCC
CLINKER     = $(CC)
CCC         = $(MPIR_HOME)/bin/mpiCC
CCLINKER    = $(CCC)
PROFILING   = $(PMPILIB)
#OPTFLAGS    = -DDEBUG -DWDEBUG -DMEMDEBUG -Wall -g -pg
#OPTFLAGS    = -D_DEBUG -DUSERTYPE=$(BASETYPE) -Wall -bind_at_load

COMPILINGRDIR = ./
MAXPENDING ?=
ifneq ($(strip $(MAXPENDING)),)
PENDING_FLAGS = -DMAXPENDING=$(MAXPENDING)
endif
#OPTFLAGS    = -D_DEBUG -Wall
OPTFLAGS=-D_DEBUG $(USER_TYPE_FLAGS) $(PENDING_FLAGS) -I$(COMPILINGRDIR)h -I.

ARCHFLAGS=-g -fstrict-aliasing -mtune=x86-64
#-mpilog -mpitrace -mpianim -02 -DWDEBUG
#OPTFLAGS    =  -DWDEBUG -DMEMDEBUG -g -pg

########per il parser
LEX=flex
YACC=bison

### End User configurable options ###
#OSFLAGS = -DLINUX
OSFLAGS	  =

BUILDDIR    = build
OBJECTS	    = $(BUILDDIR)/parser.tab.o $(BUILDDIR)/lex.yy.o $(BUILDDIR)/read_back.o $(BUILDDIR)/dvm.o $(BUILDDIR)/io.o $(BUILDDIR)/graph.o $(BUILDDIR)/symbolic.o $(BUILDDIR)/distribution.o $(BUILDDIR)/print.o $(BUILDDIR)/main.o $(BUILDDIR)/buildgraph.o $(BUILDDIR)/combustion.o $(BUILDDIR)/globals.o
SRCS	    = lex.yy.c parser.tab.c $(COMPILINGRDIR)read_back.c $(COMPILINGRDIR)dvm.c  $(COMPILINGRDIR)io.c $(COMPILINGRDIR)graph.c $(COMPILINGRDIR)symbolic.c $(COMPILINGRDIR)distribution.c $(COMPILINGRDIR)print.c $(COMPILINGRDIR)main.c $(COMPILINGRDIR)buildgraph.c $(COMPILINGRDIR)combustion.c $(COMPILINGRDIR)globals.c
PARSERSRC   = lex.yy.c parser.tab.c
EXECS       = combustion.mac

GMLDIR      = GML
LOGDIR      = LOGS
REPORTDIR   = REPORTS
SCRIPTDIR   = scripts
OUTDIR      = OUTPUT
