# Generated automatically from Makefile.in by configure.
ALL: default
##### User configurable options #####

PEXDIR      = pelcrexamples
ARCH        = LINUX
BASETYPE    = 'long long'
MPIR_HOME   = /usr/local
CC          = $(MPIR_HOME)/bin/mpicc
CCP         = $(MPIR_HOME)/bin/mpiCC
CLINKER     = $(CC)
CCC         = $(MPIR_HOME)/bin/mpiCC
COMPILINGRDIR = ./
CCLINKER    = $(CCC)
PROFILING   = $(PMPILIB)
#OPTFLAGS    = -DDEBUG -DWDEBUG -DMEMDEBUG -Wall -g -pg
OPTFLAGS    = -D_DEBUG -DWDEBUG -DMEMDEBUG  -DUSERTYPE=$(BASETYPE) -Wall -g -Wl,-export-dynamic -I $(COMPILINGRDIR)h -I .
#-mpilog -mpitrace -mpianim -02 -DWDEBUG
#OPTFLAGS    =  -DWDEBUG -DMEMDEBUG -g -pg

LIB_PATH    =
LIB_LIST    = -ldl -lm -ll -lc -lpthread

########per il parser
LEX= lex
YACC = bison

### End User configurable options ###
OSFLAGS   = -DLINUX
EXECS     = combustion.linux

BUILDDIR    = build
OBJECTS	    = $(BUILDDIR)/read_back.o $(BUILDDIR)/dvm.o $(BUILDDIR)/io.o $(BUILDDIR)/graph.o $(BUILDDIR)/symbolic.o $(BUILDDIR)/distribution.o $(BUILDDIR)/print.o $(BUILDDIR)/main.o $(BUILDDIR)/buildgraph.o $(BUILDDIR)/combustion.o $(BUILDDIR)/lex.yy.o $(BUILDDIR)/parser.tab.o $(BUILDDIR)/globals.o
SRCS	    = read_back.c dvm.c  io.c graph.c symbolic.c distribution.c print.c parser.tab.c main.c buildgraph.c combustion.c lex.yy.c globals.c
PARSERSRC   = lex.yy.c parser.tab.c

GMLDIR      = GML
LOGDIR      = LOGS
REPORTDIR   = REPORTS
SCRIPTDIR   = scripts
OUTDIR      = OUTPUT
